branch-defaults:
  default:
    environment: server-django-prod
environment-defaults:
  server-django-prod:
    branch: null
    repository: null
global:
  application_name: server_django
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
